"""Tests for the protocol module (CRC8, COBS, framing)."""

import struct

from msfs_sender.protocol import (
    cobs_decode,
    cobs_encode,
    crc8,
    frame_attitude,
    frame_engine,
    frame_flight_data,
    frame_gforce,
)


class TestCRC8:
    def test_empty(self):
        assert crc8(b"") == 0x00

    def test_zero_byte(self):
        assert crc8(b"\x00") == 0x00

    def test_different_data_different_crc(self):
        assert crc8(b"\x01") != crc8(b"\x02")

    def test_deterministic(self):
        data = b"\x01\x02\x03\xFF\x80"
        assert crc8(data) == crc8(data)

    def test_known_value(self):
        # Verify CRC8/MAXIM with polynomial 0x31
        # Single byte 0x01: shift through 8 bits
        result = crc8(b"\x01")
        assert isinstance(result, int)
        assert 0 <= result <= 255


class TestCOBS:
    def test_roundtrip_no_zeros(self):
        data = b"\x01\x02\x03"
        assert cobs_decode(cobs_encode(data)) == data

    def test_roundtrip_with_zeros(self):
        data = b"\x00\x01\x00\x02"
        assert cobs_decode(cobs_encode(data)) == data

    def test_roundtrip_all_zeros(self):
        data = b"\x00\x00\x00"
        assert cobs_decode(cobs_encode(data)) == data

    def test_roundtrip_empty(self):
        data = b""
        assert cobs_decode(cobs_encode(data)) == data

    def test_no_zeros_in_encoded(self):
        data = b"\x00\x01\x00\x02\x00"
        encoded = cobs_encode(data)
        assert 0x00 not in encoded


class TestFrameAttitude:
    def test_frame_structure(self):
        frame = frame_attitude(0, 0, 0)
        # Must start and end with 0x00
        assert frame[0] == 0x00
        assert frame[-1] == 0x00
        # No zeros in the COBS-encoded middle
        assert 0x00 not in frame[1:-1]

    def test_frame_decodable(self):
        frame = frame_attitude(450, -300, 2700)
        # Decode the COBS data between delimiters
        decoded = cobs_decode(frame[1:-1])
        # Check msg_type
        assert decoded[0] == 0x02
        # Check CRC
        payload = decoded[:-1]
        assert crc8(payload) == decoded[-1]
        # Check values
        pitch, roll, heading = struct.unpack("<hhh", decoded[1:7])
        assert pitch == 450
        assert roll == -300
        assert heading == 2700

    def test_negative_values(self):
        frame = frame_attitude(-1800, -900, 0)
        decoded = cobs_decode(frame[1:-1])
        pitch, roll, heading = struct.unpack("<hhh", decoded[1:7])
        assert pitch == -1800
        assert roll == -900
        assert heading == 0

    def test_max_values(self):
        frame = frame_attitude(1800, 1800, 3599)
        decoded = cobs_decode(frame[1:-1])
        pitch, roll, heading = struct.unpack("<hhh", decoded[1:7])
        assert pitch == 1800
        assert roll == 1800
        assert heading == 3599

    def test_byte_identical_to_rust(self):
        """Verify Python output matches Rust proto crate exactly.

        Reference bytes generated by Rust: AttitudeMsg{pitch=450, roll=-300, heading=2700}
        via: frame(MsgType::Attitude, msg.as_bytes(), &mut wire)
        """
        rust_output = bytes.fromhex("000902c201d4fe8c0a6200")
        python_output = frame_attitude(450, -300, 2700)
        assert python_output == rust_output


class TestFrameEngine:
    def test_frame_structure(self):
        frame = frame_engine(2450, 75, 128, 200, 180)
        assert frame[0] == 0x00
        assert frame[-1] == 0x00
        assert 0x00 not in frame[1:-1]

    def test_frame_decodable(self):
        frame = frame_engine(2450, 75, 128, 200, 180)
        decoded = cobs_decode(frame[1:-1])
        assert decoded[0] == 0x03
        assert crc8(decoded[:-1]) == decoded[-1]
        rpm, throttle, fuel_flow, oil_temp, oil_press = struct.unpack("<HBBBB", decoded[1:7])
        assert rpm == 2450
        assert throttle == 75
        assert fuel_flow == 128
        assert oil_temp == 200
        assert oil_press == 180

    def test_byte_identical_to_rust(self):
        """Reference bytes generated by Rust: EngineMsg{rpm=2450, throttle=75, ...}"""
        rust_output = bytes.fromhex("00090392094b80c8b47300")
        python_output = frame_engine(2450, 75, 128, 200, 180)
        assert python_output == rust_output


class TestFrameFlightData:
    def test_frame_structure(self):
        frame = frame_flight_data(1250, -50, -1500, 1400)
        assert frame[0] == 0x00
        assert frame[-1] == 0x00
        assert 0x00 not in frame[1:-1]

    def test_frame_decodable(self):
        frame = frame_flight_data(1250, -50, -1500, 1400)
        decoded = cobs_decode(frame[1:-1])
        assert decoded[0] == 0x04
        assert crc8(decoded[:-1]) == decoded[-1]
        airspeed, altitude, vspeed, ground_speed = struct.unpack("<HihH", decoded[1:11])
        assert airspeed == 1250
        assert altitude == -50
        assert vspeed == -1500
        assert ground_speed == 1400

    def test_byte_identical_to_rust(self):
        """Reference bytes generated by Rust: FlightDataMsg{airspeed=1250, altitude=-50, ...}"""
        rust_output = bytes.fromhex("000d04e204ceffffff24fa7805c700")
        python_output = frame_flight_data(1250, -50, -1500, 1400)
        assert python_output == rust_output


class TestFrameGForce:
    def test_frame_structure(self):
        frame = frame_gforce(-15, 120, 5)
        assert frame[0] == 0x00
        assert frame[-1] == 0x00
        assert 0x00 not in frame[1:-1]

    def test_frame_decodable(self):
        frame = frame_gforce(-15, 120, 5)
        decoded = cobs_decode(frame[1:-1])
        assert decoded[0] == 0x05
        assert crc8(decoded[:-1]) == decoded[-1]
        gx, gy, gz = struct.unpack("<hhh", decoded[1:7])
        assert gx == -15
        assert gy == 120
        assert gz == 5

    def test_byte_identical_to_rust(self):
        """Reference bytes generated by Rust: GForceMsg{gforce_x=-15, gforce_y=120, gforce_z=5}"""
        rust_output = bytes.fromhex("000505f1ff780205023d00")
        python_output = frame_gforce(-15, 120, 5)
        assert python_output == rust_output
